name: Run Jest Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'node'  # Always latest stable Node.js

    - name: Install dependencies
      run: npm ci

    - name: Run Jest tests
      run: npx jest
